# Generated by Django 5.2.17 on 2026-08-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم الشريك')),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('partner_type', models.CharField(choices=[('COMPANY', 'شركة'), ('FREELANCE_TRAINER', 'مدرب مستقل')], max_length=32, verbose_name='النوع')),
                ('registry_number', models.CharField(blank=True, max_length=64, verbose_name='رقم التسجيل')),
                ('registry_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('FORMER', 'سابق')], default='ACTIVE', max_length=32, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['name_ar'],
                'constraints': [models.CheckConstraint(condition=models.Q(('partner_type__in', ['COMPANY', 'FREELANCE_TRAINER'])), name='partners_partner_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'FORMER'])), name='partners_partner_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=64, unique=True, verbose_name='رقم الاتفاقية')),
                ('title_ar', models.CharField(max_length=255, verbose_name='عنوان الاتفاقية')),
                ('signed_on', models.DateField(verbose_name='تاريخ التوقيع')),
                ('valid_from', models.DateField(verbose_name='سارية من')),
                ('valid_to', models.DateField(verbose_name='سارية حتى')),
                ('calculation_model', models.CharField(choices=[('PERCENT', 'نسبة مئوية'), ('FIXED_PER_STUDENT', 'مبلغ ثابت لكل طالب'), ('SERVICE_COMMISSION', 'عمولة خدمة')], max_length=32, verbose_name='نموذج الاحتساب')),
                ('percent_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='النسبة')),
                ('fixed_amount_per_student', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='المبلغ لكل طالب')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='سعر البيع')),
                ('service_name_ar', models.CharField(blank=True, max_length=255)),
                ('service_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('exclude_registration_fee', models.BooleanField(default=True, verbose_name='استثناء رسم التسجيل')),
                ('exclude_deposits', models.BooleanField(default=True, help_text='Q-01 — الافتراض استثناء التأمين من وعاء القسمة. تعطيله يتطلب نصاً صريحاً في الاتفاقية ويُسجَّل تحذيراً (BR-092)', verbose_name='استثناء التأمينات')),
                ('exclude_consumables', models.BooleanField(default=False, verbose_name='استثناء المستهلكات')),
                ('consumables_cap_per_student', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='سقف المستهلكات لكل طالب')),
                ('discount_split_mode', models.CharField(choices=[('HALF', 'مناصفة'), ('BY_RATIO', 'بنسبة القسمة'), ('UNIVERSITY_ONLY', 'على الجامعة وحدها')], default='HALF', max_length=32, verbose_name='توزيع عبء الخصم')),
                ('payout_timing', models.CharField(choices=[('END_OF_SUBJECT', 'نهاية المادة'), ('END_OF_COURSE', 'نهاية الدورة'), ('ADVANCE', 'صرف مقدّم')], default='END_OF_COURSE', max_length=32, verbose_name='توقيت الصرف')),
                ('settlement_cycle', models.CharField(choices=[('EVERY_4_MONTHS', 'كل أربعة أشهر'), ('END_OF_COURSE', 'نهاية الدورة')], default='END_OF_COURSE', max_length=32, verbose_name='دورة المخالصة')),
                ('name_list_due_days', models.PositiveSmallIntegerField(blank=True, help_text='BR-054 — بعدها يُقفل الكشف ويُحتسب استرجاع الصرف المقدّم', null=True, verbose_name='مهلة كشف الأسماء بالأيام')),
                ('entitlement_rule_ar', models.TextField(blank=True, verbose_name='نص قاعدة الاستحقاق')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'سارية'), ('EXPIRED', 'منتهية'), ('TERMINATED', 'منهاة')], default='DRAFT', max_length=32, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='partners.agreement', verbose_name='ملحق لاتفاقية')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='partners.partner', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'اتفاقية',
                'verbose_name_plural': 'الاتفاقيات',
                'ordering': ['-signed_on', 'agreement_number'],
            },
        ),
        migrations.CreateModel(
            name='AgreementProgramSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('course_fee_at_signing', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='رسوم الدورة وقت التوقيع')),
                ('registration_fee_at_signing', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('subjects_snapshot', models.JSONField(blank=True, default=list)),
                ('level_key', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_snapshots', to='partners.agreement')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_snapshots', to='catalog.program')),
            ],
            options={
                'verbose_name': 'لقطة برنامج اتفاقية',
                'verbose_name_plural': 'لقطات برامج الاتفاقيات',
                'ordering': ['agreement', 'program'],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'program', 'level_key'), name='partners_snapshot_unique_program_level'), models.CheckConstraint(condition=models.Q(('course_fee_at_signing__gte', 0)), name='partners_snapshot_fee_not_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['partner', 'status'], name='prt_agr_partner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['valid_from', 'valid_to'], name='prt_agr_validity_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['status'], name='prt_agr_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('calculation_model__in', ['PERCENT', 'FIXED_PER_STUDENT', 'SERVICE_COMMISSION'])), name='partners_agreement_model_valid'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED'])), name='partners_agreement_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gt', models.F('valid_from'))), name='partners_agreement_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_model', 'PERCENT'), _negated=True), models.Q(('percent_rate__isnull', False), ('percent_rate__gte', 0), ('percent_rate__lte', 100)), _connector='OR'), name='partners_agreement_percent_complete'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_model', 'FIXED_PER_STUDENT'), _negated=True), models.Q(('fixed_amount_per_student__isnull', False), ('sell_price__isnull', False), ('sell_price__gte', models.F('fixed_amount_per_student'))), _connector='OR'), name='partners_agreement_fixed_complete'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_model', 'SERVICE_COMMISSION'), _negated=True), models.Q(('service_price__isnull', False), ('commission_amount__isnull', False), ('commission_amount__lte', models.F('service_price'))), _connector='OR'), name='partners_agreement_commission_complete'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_split_mode', 'BY_RATIO'), _negated=True), ('calculation_model', 'PERCENT'), _connector='OR'), name='partners_agreement_by_ratio_needs_percent'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('consumables_cap_per_student__isnull', True), ('consumables_cap_per_student__gte', 0), _connector='OR'), name='partners_agreement_cap_not_negative'),
        ),
    ]
