# Generated by Django 5.2.17 on 2026-08-14 18:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name_ar', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالعربية')),
                ('role', models.CharField(blank=True, choices=[('CENTER_MANAGER', 'مدير المركز'), ('REGISTRATION_OFFICER', 'موظف التسجيل'), ('FINANCE_OFFICER', 'الموظف المالي'), ('CASHIER', 'الصندوق'), ('AUDIT_ACCOUNT', 'حساب التدقيق'), ('SYSTEM_ADMINISTRATOR', 'مدير النظام')], help_text='الدور يأتي من المصادقة — لا واجهة تغيّره على الجلسة (D-20)', max_length=32, verbose_name='الدور')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='الدائرة')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('role', ''), ('role__in', ['CENTER_MANAGER', 'REGISTRATION_OFFICER', 'FINANCE_OFFICER', 'CASHIER', 'AUDIT_ACCOUNT', 'SYSTEM_ADMINISTRATOR']), _connector='OR'), name='people_user_role_valid')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
