# Generated by Django 5.2.17 on 2026-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='people_user_role_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات الفاشلة'),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب القفل'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='يُقفل الحساب بعد تجاوز حد المحاولات الفاشلة (Q-12)', null=True, verbose_name='تاريخ القفل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CENTER_MANAGER', 'مدير المركز'), ('REGISTRATION_OFFICER', 'موظف التسجيل'), ('FINANCE_OFFICER', 'الموظف المالي'), ('FINANCE_MANAGER', 'المدير المالي'), ('CASHIER', 'الصندوق'), ('AUDIT_ACCOUNT', 'حساب التدقيق'), ('SYSTEM_ADMINISTRATOR', 'مدير النظام')], help_text='الدور يأتي من المصادقة — لا واجهة تغيّره على الجلسة (D-20)', max_length=32, verbose_name='الدور'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', ''), ('role__in', ['CENTER_MANAGER', 'REGISTRATION_OFFICER', 'FINANCE_OFFICER', 'FINANCE_MANAGER', 'CASHIER', 'AUDIT_ACCOUNT', 'SYSTEM_ADMINISTRATOR']), _connector='OR'), name='people_user_role_valid'),
        ),
    ]
