# Generated by Django 5.2.17 on 2026-08-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_add_finance_manager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number', models.CharField(editable=False, help_text='يُولَّد آلياً: السنة(4) + النوع(1) + التسلسل(4) — BR-001', max_length=9, unique=True, verbose_name='الرقم الجامعي')),
                ('category', models.CharField(choices=[('UNIVERSITY', 'طالب جامعة / خرّيج'), ('CENTER', 'طالب مركز'), ('EMPLOYEE', 'موظف الجامعة')], max_length=32, verbose_name='الفئة')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم رباعياً بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('id_document_type', models.CharField(choices=[('NATIONAL_ID', 'رقم وطني'), ('PASSPORT', 'جواز سفر')], default='NATIONAL_ID', max_length=32, verbose_name='نوع وثيقة الهوية')),
                ('id_document_number', models.CharField(max_length=32, verbose_name='رقم وثيقة الهوية')),
                ('nationality', models.CharField(blank=True, max_length=60, verbose_name='الجنسية')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], max_length=32, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('qualification', models.CharField(blank=True, max_length=32, verbose_name='المؤهل العلمي')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='المدينة')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('po_box', models.CharField(blank=True, max_length=32, verbose_name='صندوق البريد')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('employer', models.CharField(blank=True, max_length=150, verbose_name='جهة العمل')),
                ('registered_on', models.DateField(verbose_name='تاريخ التسجيل')),
                ('no_refund_pledge_accepted', models.BooleanField(default=False, verbose_name='الإقرار بالتعهّد بعدم الاسترداد')),
                ('no_refund_pledge_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت قبول التعهّد')),
                ('is_exempt', models.BooleanField(default=False, verbose_name='معفى')),
                ('exemption_approval_ref', models.CharField(blank=True, max_length=64, verbose_name='رقم موافقة رئيس الجامعة')),
                ('exemption_approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدِّل في')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['-registered_on', 'participant_number'],
                'indexes': [models.Index(fields=['name_ar'], name='people_participant_name_idx'), models.Index(fields=['phone'], name='people_participant_phone_idx'), models.Index(fields=['category'], name='people_participant_cat_idx'), models.Index(fields=['id_document_number'], name='people_participant_iddoc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('participant_number__regex', '^[0-9]{9}$')), name='people_participant_number_format'), models.CheckConstraint(condition=models.Q(('no_refund_pledge_accepted', False), ('no_refund_pledge_at__isnull', False), _connector='OR'), name='people_participant_pledge_timestamped'), models.CheckConstraint(condition=models.Q(('is_exempt', False), models.Q(('exemption_approval_ref', ''), _negated=True), _connector='OR'), name='people_participant_exemption_has_ref'), models.CheckConstraint(condition=models.Q(('category__in', ['UNIVERSITY', 'CENTER', 'EMPLOYEE'])), name='people_participant_category_valid'), models.CheckConstraint(condition=models.Q(('id_document_type__in', ['NATIONAL_ID', 'PASSPORT'])), name='people_participant_id_doc_type_valid')],
            },
        ),
    ]
