[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
testpaths = apps tests
addopts =
    -ra
    --strict-markers
    --cov=apps/core
    --cov=apps/people
    --cov=apps/catalog
    --cov=apps/operations
    --cov=apps/billing
    --cov=apps/cashbox
    --cov-report=term-missing
    --cov-report=html:htmlcov
