# Generated by Django 5.2.17 on 2026-08-15 11:39

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('REGISTRATION', 'رسم تسجيل'), ('TUITION', 'رسوم دراسية'), ('CONSUMABLES', 'مستهلكات'), ('DEPOSIT', 'تأمين مسترد'), ('EXTRA_FEE', 'رسم إضافي'), ('TRANSFER_DIFFERENCE', 'فرق نقل')], max_length=32, verbose_name='نوع البند')),
                ('description_ar', models.CharField(max_length=255, verbose_name='البيان')),
                ('net_amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ الصافي')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='خاضع للضريبة')),
                ('tax_rate_snapshot', models.DecimalField(blank=True, decimal_places=4, help_text='لقطة وقت الإنشاء — البند القديم يحتفظ بنسبته (BR-098)', max_digits=7, null=True, verbose_name='نسبة الضريبة المطبَّقة')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مبلغ الضريبة')),
                ('gross_amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الإجمالي المطلوب')),
                ('charged_on', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('is_partner_shareable', models.BooleanField(default=True, help_text='يُحسم وقت الإنشاء من الاتفاقية — BR-046', verbose_name='يدخل وعاء الشريك')),
                ('is_revenue', models.BooleanField(default=True, help_text='False للتأمينات — التزام لا إيراد (BR-092)', verbose_name='يُحتسب إيراداً')),
                ('deposit_policy_snapshot', models.JSONField(blank=True, help_text='للتأمينات فقط — تغيير السياسة لاحقاً لا يمسّ بنداً قائماً', null=True, verbose_name='لقطة سياسة التأمين')),
                ('voided', models.BooleanField(default=False, verbose_name='ملغى')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason_ar', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_lines', to='operations.enrollment', verbose_name='التسجيل')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_lines', to='catalog.subject', verbose_name='المادة')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_charge_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بند رسم',
                'verbose_name_plural': 'بنود الرسوم',
                'ordering': ['enrollment', 'charged_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepositForfeiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المُصادَر')),
                ('reason', models.CharField(max_length=32, verbose_name='سبب المصادرة')),
                ('justification_ar', models.TextField(verbose_name='المبرر')),
                ('forfeited_on', models.DateField(verbose_name='تاريخ المصادرة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forfeitures_approved', to=settings.AUTH_USER_MODEL)),
                ('deposit_charge_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forfeitures', to='billing.chargeline', verbose_name='بند التأمين الأصلي')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_forfeitures', to='operations.enrollment')),
                ('forfeited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forfeitures_made', to=settings.AUTH_USER_MODEL)),
                ('revenue_charge_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forfeiture_source', to='billing.chargeline', verbose_name='بند الإيراد الناتج')),
            ],
            options={
                'verbose_name': 'مصادرة تأمين',
                'verbose_name_plural': 'مصادرات التأمين',
                'ordering': ['-forfeited_on'],
            },
        ),
        migrations.CreateModel(
            name='DepositReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المُعاد')),
                ('trigger', models.CharField(max_length=32, verbose_name='مُحفّز الاسترداد')),
                ('returned_on', models.DateField(verbose_name='تاريخ الإعادة')),
                ('deduction_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الحسم الجزئي')),
                ('deduction_reason_ar', models.TextField(blank=True, verbose_name='سبب الحسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_charge_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.chargeline', verbose_name='بند التأمين')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_returns', to='operations.enrollment')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعادة تأمين',
                'verbose_name_plural': 'إعادات التأمين',
                'ordering': ['-returned_on'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'نسبة'), ('AMOUNT', 'مبلغ')], max_length=32, verbose_name='نوع الخصم')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='النسبة')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مبلغ الخصم')),
                ('base_amount', models.DecimalField(decimal_places=3, help_text='منسوخ — لا يُعاد حسابه إن تغيّرت الرسوم لاحقاً', max_digits=12, verbose_name='الوعاء وقت الاحتساب')),
                ('reason_ar', models.CharField(max_length=255, verbose_name='السبب')),
                ('president_approval_ref', models.CharField(max_length=64, verbose_name='رقم موافقة رئيس الجامعة')),
                ('president_approval_date', models.DateField(verbose_name='تاريخ الموافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('university_burden', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='حصة الجامعة من الخصم')),
                ('partner_burden', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='حصة الشريك من الخصم')),
                ('discount_split_mode_snapshot', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='operations.enrollment')),
            ],
            options={
                'verbose_name': 'خصم',
                'verbose_name_plural': 'الخصومات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('SUBJECT_REPEAT', 'إعادة مادة'), ('CERTIFICATE_REPLACEMENT', 'بدل فاقد شهادة'), ('INTERNATIONAL_EXAM', 'امتحان دولي'), ('OTHER', 'أخرى')], max_length=32, verbose_name='نوع الرسم')),
                ('subject_name', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ')),
                ('is_partner_shareable', models.BooleanField(default=False)),
                ('prior_agreement_with_participant', models.BooleanField(default=False, help_text='BR-040 — لا رسم إضافي بلا علم المشارك', verbose_name='اتفاق مسبق مع المشارك')),
                ('charged_on', models.DateField()),
                ('charge_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_fee_source', to='billing.chargeline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_fees_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_fees', to='operations.enrollment')),
            ],
            options={
                'verbose_name': 'رسم إضافي',
                'verbose_name_plural': 'الرسوم الإضافية',
                'ordering': ['-charged_on'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('refund_type', models.CharField(max_length=32, verbose_name='نوع الاسترداد')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ')),
                ('reason_ar', models.TextField(verbose_name='السبب')),
                ('official_letter_ref', models.CharField(max_length=64, verbose_name='مرجع الكتاب الرسمي')),
                ('official_letter_date', models.DateField(blank=True, null=True)),
                ('president_approval_ref', models.CharField(max_length=64, verbose_name='رقم موافقة رئيس الجامعة')),
                ('president_approval_date', models.DateField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'مطلوب'), ('APPROVED', 'معتمد'), ('EXECUTED', 'منفَّذ'), ('REJECTED', 'مرفوض')], default='REQUESTED', max_length=32)),
                ('partner_recovery_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='operations.enrollment')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_executed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استرداد',
                'verbose_name_plural': 'الاستردادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chargeline',
            index=models.Index(fields=['enrollment', 'charge_type'], name='bil_cl_enr_type_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeline',
            index=models.Index(fields=['enrollment', 'voided'], name='bil_cl_enr_voided_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeline',
            index=models.Index(fields=['charged_on'], name='bil_cl_charged_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeline',
            index=models.Index(fields=['charge_type', 'is_partner_shareable'], name='bil_cl_type_share_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeline',
            index=models.Index(fields=['is_revenue'], name='bil_cl_revenue_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeline',
            index=models.Index(fields=['is_taxable'], name='bil_cl_taxable_idx'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(('charge_type__in', ['REGISTRATION', 'TUITION', 'CONSUMABLES', 'DEPOSIT', 'EXTRA_FEE', 'TRANSFER_DIFFERENCE'])), name='billing_charge_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0), ('tax_amount__gte', 0)), name='billing_charge_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(models.F('net_amount'), '+', models.F('tax_amount')))), name='billing_charge_gross_equals_net_plus_tax'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_taxable', True), ('tax_rate_snapshot__isnull', False)), models.Q(('is_taxable', False), ('tax_amount', 0), ('tax_rate_snapshot__isnull', True)), _connector='OR'), name='billing_charge_tax_rate_captured'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('charge_type', 'DEPOSIT'), _negated=True), ('is_revenue', False), _connector='OR'), name='billing_charge_deposit_is_not_revenue'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(('charge_type', 'DEPOSIT'), ('is_revenue', True), _connector='OR'), name='billing_charge_non_deposit_is_revenue'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('charge_type', 'DEPOSIT'), _negated=True), ('deposit_policy_snapshot__isnull', False), _connector='OR'), name='billing_charge_deposit_has_policy_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(('voided', False), models.Q(('voided_by__isnull', False), models.Q(('void_reason_ar', ''), _negated=True)), _connector='OR'), name='billing_charge_void_is_explained'),
        ),
        migrations.AddConstraint(
            model_name='depositforfeiture',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_forfeiture_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='depositforfeiture',
            constraint=models.CheckConstraint(condition=models.Q(('justification_ar', ''), _negated=True), name='billing_forfeiture_has_justification'),
        ),
        migrations.AddConstraint(
            model_name='depositforfeiture',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('forfeited_by')), _negated=True), _connector='OR'), name='billing_forfeiture_approver_differs'),
        ),
        migrations.AddConstraint(
            model_name='depositreturn',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('deduction_amount__gte', 0)), name='billing_deposit_return_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='depositreturn',
            constraint=models.CheckConstraint(condition=models.Q(('deduction_amount', 0), models.Q(('deduction_reason_ar', ''), _negated=True), _connector='OR'), name='billing_deposit_deduction_is_explained'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_discount_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('president_approval_ref', ''), _negated=True), name='billing_discount_has_approval_ref'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(models.F('university_burden'), '+', models.F('partner_burden')))), name='billing_discount_burdens_sum_to_amount'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='billing_discount_approver_differs'),
        ),
        migrations.AddConstraint(
            model_name='extrafee',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_extra_fee_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['REQUESTED', 'APPROVED', 'EXECUTED', 'REJECTED'])), name='billing_refund_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('official_letter_ref', ''), _negated=True), models.Q(('president_approval_ref', ''), _negated=True)), name='billing_refund_has_external_approvals'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'EXECUTED'), _negated=True), ('executed_at__isnull', False), _connector='OR'), name='billing_refund_executed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='billing_refund_approver_differs'),
        ),
    ]
