# Generated by Django 5.2.17 on 2026-08-15 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('cashbox', '0001_initial'),
        ('operations', '0003_sprint6_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز ردّ الرصيد')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المُعاد')),
                ('reason_ar', models.TextField(verbose_name='سبب الرصيد الدائن')),
                ('returned_on', models.DateField(verbose_name='تاريخ الإعادة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_returns', to='operations.enrollment')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_returns', to=settings.AUTH_USER_MODEL)),
                ('reversal_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_returns', to='cashbox.paymentallocation', verbose_name='التخصيص العكسي')),
            ],
            options={
                'verbose_name': 'ردّ رصيد دائن',
                'verbose_name_plural': 'ردود الأرصدة الدائنة',
                'ordering': ['-returned_on', 'code'],
                'indexes': [models.Index(fields=['enrollment'], name='bil_credret_enr_idx'), models.Index(fields=['returned_on'], name='bil_credret_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_credit_return_amount_positive'), models.CheckConstraint(condition=models.Q(('reason_ar', ''), _negated=True), name='billing_credit_return_has_reason')],
            },
        ),
    ]
