# Generated by Django 5.2.17 on 2026-08-22 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_credit_return'),
        ('catalog', '0001_initial'),
        ('datamigration', '0001_initial'),
        ('operations', '0005_clearance_participant_ack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز الرصيد الافتتاحي')),
                ('source_workbook', models.CharField(blank=True, max_length=255, verbose_name='الملف المصدر')),
                ('source_sheet', models.CharField(blank=True, max_length=120, verbose_name='الورقة المصدر')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='الصف المصدر')),
                ('source_legacy_number', models.CharField(blank=True, max_length=32, verbose_name='الرقم الجامعي القديم')),
                ('direction', models.CharField(choices=[('RECEIVABLE', 'ذمة على المشارك'), ('CREDIT', 'رصيد دائن للمشارك')], max_length=32, verbose_name='اتجاه الرصيد')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ')),
                ('as_of', models.DateField(verbose_name='الرصيد كما في تاريخ')),
                ('description_ar', models.CharField(max_length=255, verbose_name='البيان')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEWED', 'مُراجَع'), ('APPROVED', 'معتمَد'), ('POSTED', 'مُرحَّل إلى الدفتر'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=32, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note_ar', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة المراجعة')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note_ar', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة القرار')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'رصيد افتتاحي',
                'verbose_name_plural': 'الأرصدة الافتتاحية',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='chargeline',
            name='billing_charge_type_valid',
        ),
        migrations.AlterField(
            model_name='chargeline',
            name='charge_type',
            field=models.CharField(choices=[('REGISTRATION', 'رسم تسجيل'), ('TUITION', 'رسوم دراسية'), ('CONSUMABLES', 'مستهلكات'), ('DEPOSIT', 'تأمين مسترد'), ('EXTRA_FEE', 'رسم إضافي'), ('TRANSFER_DIFFERENCE', 'فرق نقل'), ('OPENING_BALANCE', 'رصيد افتتاحي')], max_length=32, verbose_name='نوع البند'),
        ),
        migrations.AddConstraint(
            model_name='chargeline',
            constraint=models.CheckConstraint(condition=models.Q(('charge_type__in', ['REGISTRATION', 'TUITION', 'CONSUMABLES', 'DEPOSIT', 'EXTRA_FEE', 'TRANSFER_DIFFERENCE', 'OPENING_BALANCE'])), name='billing_charge_type_valid'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_created', to=settings.AUTH_USER_MODEL, verbose_name='اقترحه'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='operations.enrollment', verbose_name='التسجيل'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_posted', to=settings.AUTH_USER_MODEL, verbose_name='رحّله'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='posted_charge_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance', to='billing.chargeline', verbose_name='بند الرسم الناتج'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='راجعه'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='source_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='datamigration.historicalenrollment', verbose_name='الصف التاريخي المصدر'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['status'], name='bil_ob_status_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['direction', 'status'], name='bil_ob_dir_status_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['enrollment'], name='bil_ob_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['source_legacy_number'], name='bil_ob_legacy_idx'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEWED', 'APPROVED', 'POSTED', 'REJECTED'])), name='billing_opening_balance_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['RECEIVABLE', 'CREDIT'])), name='billing_opening_balance_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_opening_balance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), models.Q(('reviewed_by', models.F('created_by')), _negated=True), _connector='OR'), name='billing_opening_balance_reviewer_differs'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(models.Q(('approved_by', models.F('created_by')), _negated=True), models.Q(('approved_by', models.F('reviewed_by')), _negated=True)), _connector='OR'), name='billing_opening_balance_approver_differs'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVIEWED'), _negated=True), models.Q(('reviewed_by__isnull', False), ('reviewed_at__isnull', False)), _connector='OR'), name='billing_opening_balance_reviewed_is_stamped'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False), ('reviewed_by__isnull', False), ('enrollment__isnull', False)), _connector='OR'), name='billing_opening_balance_approved_is_stamped'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'POSTED'), _negated=True), models.Q(('posted_charge_line__isnull', False), ('posted_by__isnull', False), ('posted_at__isnull', False)), _connector='OR'), name='billing_opening_balance_posted_has_line'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('posted_charge_line__isnull', True), ('status', 'POSTED'), _connector='OR'), name='billing_opening_balance_line_implies_posted'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'CREDIT'), _negated=True), ('posted_charge_line__isnull', True), _connector='OR'), name='billing_opening_balance_credit_is_not_posted'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('source_enrollment__isnull', False)), fields=('source_enrollment',), name='billing_opening_balance_one_per_source_row'),
        ),
    ]
