# Generated by Django 5.2.17 on 2026-08-22 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_openingbalance_and_more'),
        ('datamigration', '0001_initial'),
        ('operations', '0005_clearance_participant_ack'),
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='openingbalance',
            name='billing_opening_balance_status_valid',
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='people.participant', verbose_name='المشارك'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='resolution_note_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='مسوّغ التسوية'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_resolved', to=settings.AUTH_USER_MODEL, verbose_name='سوّاه'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEWED', 'مُراجَع'), ('APPROVED', 'معتمَد'), ('POSTED', 'مُرحَّل إلى الدفتر'), ('APPLIED', 'مُرحَّل لتسجيل لاحق'), ('REFUND_DUE', 'مستحق الردّ نقداً'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=32, verbose_name='الحالة'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['participant', 'status'], name='bil_ob_part_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEWED', 'APPROVED', 'POSTED', 'APPLIED', 'REFUND_DUE', 'REJECTED'])), name='billing_opening_balance_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPLIED', 'REFUND_DUE']), _negated=True), ('direction', 'CREDIT'), _connector='OR'), name='billing_opening_balance_credit_outcomes_are_credits'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPLIED', 'REFUND_DUE']), _negated=True), models.Q(('resolved_by__isnull', False), ('resolved_at__isnull', False)), _connector='OR'), name='billing_opening_balance_resolution_is_stamped'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPLIED'), _negated=True), ('enrollment__isnull', False), _connector='OR'), name='billing_opening_balance_applied_has_enrollment'),
        ),
    ]
