# Generated by Django 5.2.17 on 2026-08-22 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_openingbalance_billing_opening_balance_status_valid_and_more'),
        ('cashbox', '0001_initial'),
        ('datamigration', '0001_initial'),
        ('operations', '0005_clearance_participant_ack'),
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز الصرف')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المصروف')),
                ('paid_on', models.DateField(verbose_name='تاريخ الصرف')),
                ('external_reference', models.CharField(max_length=64, verbose_name='رقم سند الصرف')),
                ('payee_name_ar', models.CharField(max_length=150, verbose_name='اسم المستلم')),
                ('note_ar', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صرف رصيد افتتاحي دائن',
                'verbose_name_plural': 'صرف الأرصدة الافتتاحية الدائنة',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='openingbalance',
            name='billing_opening_balance_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='openingbalance',
            name='billing_opening_balance_credit_outcomes_are_credits',
        ),
        migrations.RemoveConstraint(
            model_name='openingbalance',
            name='billing_opening_balance_resolution_is_stamped',
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEWED', 'مُراجَع'), ('APPROVED', 'معتمَد'), ('POSTED', 'مُرحَّل إلى الدفتر'), ('APPLIED', 'مُرحَّل لتسجيل لاحق'), ('REFUND_DUE', 'مستحق الردّ نقداً'), ('REFUNDED', 'رُدّ نقداً'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=32, verbose_name='الحالة'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEWED', 'APPROVED', 'POSTED', 'APPLIED', 'REFUND_DUE', 'REFUNDED', 'REJECTED'])), name='billing_opening_balance_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPLIED', 'REFUND_DUE', 'REFUNDED']), _negated=True), ('direction', 'CREDIT'), _connector='OR'), name='billing_opening_balance_credit_outcomes_are_credits'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPLIED', 'REFUND_DUE', 'REFUNDED']), _negated=True), models.Q(('resolved_by__isnull', False), ('resolved_at__isnull', False)), _connector='OR'), name='billing_opening_balance_resolution_is_stamped'),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='opening_balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_payout', to='billing.openingbalance', verbose_name='الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_refunds_paid', to=settings.AUTH_USER_MODEL, verbose_name='صرفه'),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_refunds', to='cashbox.paymentmethod', verbose_name='طريقة الصرف'),
        ),
        migrations.AddIndex(
            model_name='openingbalancerefund',
            index=models.Index(fields=['paid_on'], name='bil_obref_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalancerefund',
            index=models.Index(fields=['payment_method'], name='bil_obref_method_idx'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_ob_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerefund',
            constraint=models.CheckConstraint(condition=models.Q(('external_reference', ''), _negated=True), name='billing_ob_refund_has_voucher'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerefund',
            constraint=models.CheckConstraint(condition=models.Q(('payee_name_ar', ''), _negated=True), name='billing_ob_refund_has_payee'),
        ),
    ]
