# Generated by Django 5.2.17 on 2026-08-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_openingbalancerefund_and_more'),
        ('cashbox', '0001_initial'),
        ('datamigration', '0001_initial'),
        ('operations', '0005_clearance_participant_ack'),
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='openingbalance',
            name='billing_opening_balance_one_per_source_row',
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='active_key',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='reversal_reason_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='سبب عكس الصرف'),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='reversal_reference',
            field=models.CharField(blank=True, max_length=64, verbose_name='مرجع التصحيح'),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_refunds_reversed', to=settings.AUTH_USER_MODEL, verbose_name='عكسه'),
        ),
        migrations.AddField(
            model_name='openingbalancerefund',
            name='reversed_on',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ عكس الصرف'),
        ),
        migrations.AlterField(
            model_name='openingbalancerefund',
            name='opening_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_payouts', to='billing.openingbalance', verbose_name='الرصيد الافتتاحي'),
        ),
        migrations.AddIndex(
            model_name='openingbalancerefund',
            index=models.Index(fields=['reversed_on'], name='bil_obref_reversed_idx'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.UniqueConstraint(fields=('source_enrollment',), name='billing_opening_balance_one_per_source_row'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerefund',
            constraint=models.UniqueConstraint(fields=('opening_balance', 'active_key'), name='billing_ob_refund_one_live_per_balance'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerefund',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_at__isnull', True), models.Q(('reversed_by__isnull', False), ('reversed_on__isnull', False), models.Q(('reversal_reason_ar', ''), _negated=True)), _connector='OR'), name='billing_ob_refund_reversal_is_explained'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerefund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_key', 1), ('reversed_at__isnull', True)), models.Q(('active_key__isnull', True), ('reversed_at__isnull', False)), _connector='OR'), name='billing_ob_refund_active_key_matches_reversal'),
        ),
    ]
