# Generated by Django 5.2.17 on 2026-08-15 11:39

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0003_audit_auth_actions'),
        ('operations', '0001_initial'),
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الطريقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز الإقفال')),
                ('closing_date', models.DateField(verbose_name='تاريخ الإقفال')),
                ('system_total', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='إجمالي النظام')),
                ('counted_total', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='العدّ الفعلي')),
                ('variance', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الفرق')),
                ('receipt_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('VARIANCE_PENDING', 'فرق قيد المطابقة'), ('RECONCILED', 'مطابق مقفل')], default='OPEN', max_length=32)),
                ('variance_resolution_ar', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closings_approved', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closings', to=settings.AUTH_USER_MODEL, verbose_name='القابض')),
            ],
            options={
                'verbose_name': 'إقفال يومي',
                'verbose_name_plural': 'الإقفالات اليومية',
                'ordering': ['-closing_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_receipt_number', models.CharField(help_text='gapless سنوي من NumberSequence — المرجع النظامي (Q-03)', max_length=64, unique=True, verbose_name='رقم السند الداخلي')),
                ('external_receipt_ref', models.CharField(blank=True, help_text='من الدائرة المالية أو الدفتر الورقي — اختياري', max_length=64, verbose_name='رقم السند الخارجي')),
                ('received_on', models.DateField(verbose_name='تاريخ القبض')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المقبوض')),
                ('breakdown_text_ar', models.CharField(blank=True, max_length=255)),
                ('voucher_received', models.BooleanField(default=False)),
                ('voucher_received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'صادر'), ('VOIDED', 'ملغى')], default='ISSUED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_ref_key', models.CharField(default=None, editable=False, max_length=64, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_taken', to=settings.AUTH_USER_MODEL, verbose_name='القابض')),
                ('daily_closing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cashbox.dailyclosing')),
                ('financial_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.financialperiod', verbose_name='الفترة المالية')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='people.participant', verbose_name='المشارك')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cashbox.paymentmethod', verbose_name='طريقة الدفع')),
                ('voucher_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-received_on', '-internal_receipt_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المخصَّص')),
                ('allocation_type', models.CharField(choices=[('AUTOMATIC', 'آلي'), ('MANUAL', 'يدوي')], default='AUTOMATIC', max_length=32)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('manual_reason_ar', models.CharField(blank=True, max_length=255)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations_made', to=settings.AUTH_USER_MODEL)),
                ('charge_line', models.ForeignKey(blank=True, help_text='فارغ = رصيد دائن غير مخصَّص (BR-023)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.chargeline', verbose_name='بند الرسم')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='operations.enrollment', verbose_name='التسجيل')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverses', to='cashbox.paymentallocation', verbose_name='التخصيص العكسي')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cashbox.receipt', verbose_name='السند')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة',
                'verbose_name_plural': 'تخصيصات الدفعات',
                'ordering': ['receipt', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptVoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reason_ar', models.TextField(verbose_name='سبب الإلغاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voids_approved', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='void_record', to='cashbox.receipt', verbose_name='السند')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voids_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إلغاء سند',
                'verbose_name_plural': 'إلغاءات السندات',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'VARIANCE_PENDING', 'RECONCILED'])), name='cashbox_closing_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.UniqueConstraint(fields=('closing_date', 'cashier'), name='cashbox_closing_unique_day_cashier'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.CheckConstraint(condition=models.Q(('variance', django.db.models.expressions.CombinedExpression(models.F('counted_total'), '-', models.F('system_total')))), name='cashbox_closing_variance_is_difference'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RECONCILED'), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='cashbox_closing_reconciled_is_approved'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RECONCILED'), _negated=True), ('variance', 0), models.Q(('variance_resolution_ar', ''), _negated=True), _connector='OR'), name='cashbox_closing_variance_is_explained'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('cashier')), _negated=True), _connector='OR'), name='cashbox_closing_approver_is_not_cashier'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['received_on', 'cashier'], name='cash_rcpt_date_cashier_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['participant'], name='cash_rcpt_participant_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['daily_closing'], name='cash_rcpt_closing_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'received_on'], name='cash_rcpt_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ISSUED', 'VOIDED'])), name='cashbox_receipt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cashbox_receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('voucher_received', False), ('voucher_received_at__isnull', False), _connector='OR'), name='cashbox_receipt_voucher_timestamped'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('external_ref_key',), name='cashbox_receipt_external_ref_unique'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['receipt'], name='cash_alloc_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['charge_line'], name='cash_alloc_chargeline_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['enrollment', 'allocated_at'], name='cash_alloc_enr_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='cashbox_allocation_amount_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_type', 'MANUAL'), _negated=True), models.Q(('allocated_by__isnull', False), models.Q(('manual_reason_ar', ''), _negated=True)), _connector='OR'), name='cashbox_allocation_manual_is_explained'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoid',
            constraint=models.CheckConstraint(condition=models.Q(('reason_ar', ''), _negated=True), name='cashbox_void_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoid',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='cashbox_void_approver_differs'),
        ),
    ]
