# Generated by Django 5.2.17 on 2026-09-19 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoid',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoid',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voids_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptvoid',
            name='rejection_reason_ar',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoid',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_by__isnull', True), models.Q(('rejected_by', models.F('requested_by')), _negated=True), _connector='OR'), name='cashbox_void_rejecter_differs'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoid',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), ('rejected_by__isnull', True), _connector='OR'), name='cashbox_void_one_decision'),
        ),
    ]
