# Generated by Django 5.2.17 on 2026-09-19 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_void_rejection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closings_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='unvouched_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
