# Generated by Django 5.2.17 on 2026-08-14 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='الوقت')),
                ('actor_role', models.CharField(blank=True, max_length=32, verbose_name='الدور وقت الحدث')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('APPROVE', 'اعتماد'), ('REJECT', 'رفض'), ('VOID', 'إلغاء'), ('RECEIVE_CASH', 'قبض'), ('LOGIN', 'دخول'), ('LOGOUT', 'خروج'), ('VIEW_SENSITIVE', 'عرض حساس'), ('DENIED_ATTEMPT', 'محاولة مرفوضة'), ('SETTING_CHANGE', 'تغيير إعداد')], max_length=32, verbose_name='الإجراء')),
                ('entity_type', models.CharField(max_length=32, verbose_name='الكيان')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='مُعرِّف الكيان')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='المرجع المعروض')),
                ('summary_ar', models.CharField(max_length=500, verbose_name='التفصيل')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('denial_rule', models.CharField(blank=True, max_length=32, verbose_name='القاعدة المانعة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('prev_hash', models.CharField(editable=False, max_length=64, verbose_name='البصمة السابقة')),
                ('row_hash', models.CharField(editable=False, max_length=64, verbose_name='بصمة السجل')),
            ],
            options={
                'verbose_name': 'قيد تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EffectiveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, verbose_name='المفتاح')),
                ('value', models.CharField(blank=True, help_text='NULL تعني «غير محدَّدة بعد» ولا تعني صفراً', max_length=255, null=True, verbose_name='القيمة')),
                ('value_type', models.CharField(choices=[('DECIMAL', 'رقم عشري'), ('INTEGER', 'رقم صحيح'), ('BOOLEAN', 'منطقي'), ('STRING', 'نص')], max_length=32, verbose_name='نوع القيمة')),
                ('effective_from', models.DateField(verbose_name='سارٍ من')),
                ('effective_to', models.DateField(blank=True, help_text='فارغ = سارٍ حتى إشعار آخر', null=True, verbose_name='سارٍ حتى')),
                ('note', models.TextField(verbose_name='مبرر التغيير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
            ],
            options={
                'verbose_name': 'إعداد مؤرّخ',
                'verbose_name_plural': 'الإعدادات المؤرّخة',
                'ordering': ['key', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(verbose_name='تبدأ في')),
                ('ends_on', models.DateField(verbose_name='تنتهي في')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مقفلة')], default='OPEN', max_length=32, verbose_name='الحالة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإقفال')),
            ],
            options={
                'verbose_name': 'فترة مالية',
                'verbose_name_plural': 'الفترات المالية',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='participant · receipt · certificate · agreement', max_length=32, verbose_name='النطاق')),
                ('partition', models.CharField(help_text='مثال: 2026 أو 2026-5 أو legacy-2018', max_length=32, verbose_name='التقسيم')),
                ('next_value', models.BigIntegerField(default=1, verbose_name='القيمة التالية')),
                ('padding', models.PositiveSmallIntegerField(default=4, verbose_name='عدد الخانات')),
                ('is_gapless', models.BooleanField(default=True, help_text='الأرقام المالية بلا فجوات — الفجوة شبهة تدقيق', verbose_name='بلا فجوات')),
            ],
            options={
                'verbose_name': 'عدّاد ترقيم',
                'verbose_name_plural': 'عدّادات الترقيم',
                'ordering': ['scope', 'partition'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم الفصل')),
                ('type_code', models.PositiveSmallIntegerField(choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني'), (3, 'الفصل الصيفي')], verbose_name='رمز النوع')),
                ('academic_year', models.CharField(max_length=9, verbose_name='السنة الدراسية')),
                ('starts_on', models.DateField(verbose_name='يبدأ في')),
                ('ends_on', models.DateField(verbose_name='ينتهي في')),
                ('is_active', models.BooleanField(default=False, verbose_name='الفصل الحالي')),
                ('active_flag', models.BooleanField(default=None, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('TRAINER_CV', 'السيرة الذاتية للمدرب'), ('ENTITY_LICENSE', 'تراخيص الجهة'), ('OFFICIAL_LETTER', 'كتاب رسمي'), ('PRESIDENT_APPROVAL', 'موافقة رئيس الجامعة'), ('SIGNED_AGREEMENT', 'اتفاقية موقّعة'), ('SETTLEMENT', 'مخالصة موقّعة'), ('INVOICE', 'فاتورة'), ('OTHER', 'أخرى')], max_length=32, verbose_name='الغرض')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع المحتوى')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='الحجم')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='البصمة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرفع')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
