# Generated by Django 5.2.17 on 2026-08-14 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='رفعه'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='effectivesetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_settings', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه'),
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_financial_periods', to=settings.AUTH_USER_MODEL, verbose_name='أقفلها'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(fields=('scope', 'partition'), name='core_sequence_unique_scope_partition'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.CheckConstraint(condition=models.Q(('next_value__gte', 1)), name='core_sequence_next_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.CheckConstraint(condition=models.Q(('padding__gte', 1), ('padding__lte', 12)), name='core_sequence_padding_range'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_active'], name='core_semester_active_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['starts_on', 'ends_on'], name='core_semester_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='core_semester_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('type_code__in', [1, 2, 3])), name='core_semester_type_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('active_flag',), name='core_semester_single_active'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id', 'purpose'], name='core_attachment_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0), ('size_bytes__lte', 10485760)), name='core_attachment_size_within_limit'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='core_audit_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='core_audit_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'occurred_at'], name='core_audit_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'DENIED_ATTEMPT'), _negated=True), models.Q(('denial_rule', ''), _negated=True), _connector='OR'), name='core_audit_denied_requires_rule'),
        ),
        migrations.AddIndex(
            model_name='effectivesetting',
            index=models.Index(fields=['key', 'effective_from'], name='core_setting_key_from_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivesetting',
            index=models.Index(fields=['key', 'effective_to'], name='core_setting_key_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='effectivesetting',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='core_setting_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='effectivesetting',
            constraint=models.UniqueConstraint(fields=('key', 'effective_from'), name='core_setting_unique_key_from'),
        ),
        migrations.AddIndex(
            model_name='financialperiod',
            index=models.Index(fields=['starts_on', 'ends_on'], name='core_period_range_idx'),
        ),
        migrations.AddIndex(
            model_name='financialperiod',
            index=models.Index(fields=['status'], name='core_period_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='core_period_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('closed_by__isnull', False), ('closed_at__isnull', False)), _connector='OR'), name='core_period_closed_requires_closer'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.UniqueConstraint(fields=('starts_on',), name='core_period_unique_start'),
        ),
    ]
