# Generated by Django 5.2.17 on 2026-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('APPROVE', 'اعتماد'), ('REJECT', 'رفض'), ('VOID', 'إلغاء'), ('RECEIVE_CASH', 'قبض'), ('LOGIN', 'دخول'), ('LOGOUT', 'خروج'), ('LOGIN_FAILED', 'محاولة دخول فاشلة'), ('ACCOUNT_LOCKED', 'قفل حساب'), ('ACCOUNT_UNLOCKED', 'فكّ قفل حساب'), ('SESSION_EXPIRED', 'انتهاء جلسة للخمول'), ('VIEW_SENSITIVE', 'عرض حساس'), ('DENIED_ATTEMPT', 'محاولة مرفوضة'), ('SETTING_CHANGE', 'تغيير إعداد')], max_length=32, verbose_name='الإجراء'),
        ),
    ]
