# Generated by Django 5.2.17 on 2026-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_auth_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='entity_type',
            field=models.CharField(max_length=64, verbose_name='الكيان'),
        ),
    ]
