# Generated by Django 5.2.17 on 2026-09-25 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditevent_entity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('LOGO_PRIMARY', 'شعار الشاشة'), ('LOGO_PRINT', 'شعار الطباعة'), ('WATERMARK', 'العلامة المائية'), ('FAVICON', 'أيقونة المتصفح')], db_index=True, max_length=32, verbose_name='الموضع')),
                ('file', models.FileField(upload_to='branding/%Y/%m/', verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع المحتوى')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='الحجم')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='البصمة')),
                ('width_px', models.PositiveIntegerField(blank=True, null=True, verbose_name='العرض')),
                ('height_px', models.PositiveIntegerField(blank=True, null=True, verbose_name='الارتفاع')),
                ('alt_text_ar', models.CharField(blank=True, help_text='ما يقرؤه قارئ الشاشة مكان الصورة', max_length=200, verbose_name='النص البديل')),
                ('effective_from', models.DateField(verbose_name='سارٍ من')),
                ('effective_to', models.DateField(blank=True, help_text='فارغ = سارٍ حتى إشعار آخر', null=True, verbose_name='سارٍ حتى')),
                ('note', models.TextField(verbose_name='مبرّر التغيير')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرفع')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_brand_assets', to=settings.AUTH_USER_MODEL, verbose_name='رفعه')),
            ],
            options={
                'verbose_name': 'عنصر هوية',
                'verbose_name_plural': 'عناصر الهوية',
                'ordering': ['slot', '-effective_from'],
                'indexes': [models.Index(fields=['slot', 'effective_from'], name='core_brand_slot_from_idx'), models.Index(fields=['slot', 'effective_to'], name='core_brand_slot_to_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='core_brand_asset_period_valid'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='core_brand_asset_has_content'), models.UniqueConstraint(fields=('slot', 'effective_from'), name='core_brand_asset_unique_slot_from')],
            },
        ),
    ]
