# Generated by Django 5.2.17 on 2026-08-21 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=120, verbose_name='الورقة')),
                ('program_label_ar', models.CharField(blank=True, max_length=150, verbose_name='البرنامج')),
                ('term_label', models.CharField(blank=True, max_length=120, verbose_name='الفصل')),
                ('partner_label_ar', models.CharField(blank=True, max_length=150, verbose_name='الشريك')),
                ('delivery_label', models.CharField(blank=True, max_length=60, verbose_name='نمط التقديم')),
                ('date_label', models.CharField(blank=True, max_length=120, verbose_name='التاريخ كما ورد')),
                ('subject_prices', models.JSONField(blank=True, default=dict, verbose_name='أسعار المواد')),
            ],
            options={
                'verbose_name': 'دفعة تاريخية',
                'verbose_name_plural': 'الدفعات التاريخية',
                'ordering': ['batch', 'sheet_name'],
            },
        ),
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز الدفعة')),
                ('source_filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='بصمة الملف')),
                ('sheet_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأوراق')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفوف المقروءة')),
                ('sheet_headers', models.JSONField(blank=True, default=dict, verbose_name='رؤوس الأوراق')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('VALIDATED', 'مُدقَّقة'), ('COMMITTED', 'مؤرشفة'), ('SUPERSEDED', 'مستبدَلة')], default='DRAFT', max_length=32, verbose_name='الحالة')),
                ('note_ar', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migration_batches_committed', to=settings.AUTH_USER_MODEL, verbose_name='أرشفها')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migration_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='استوردها')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='datamigration.migrationbatch', verbose_name='استُبدلت بـ')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migration_batches_validated', to=settings.AUTH_USER_MODEL, verbose_name='دقّقها')),
            ],
            options={
                'verbose_name': 'دفعة ترحيل',
                'verbose_name_plural': 'دفعات الترحيل',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_number', models.CharField(max_length=32, verbose_name='الرقم الجامعي القديم')),
                ('legacy_alt_number', models.CharField(blank=True, max_length=32, verbose_name='الرقم الثاني في الخلية')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='الاسم كما ورد')),
                ('legacy_category', models.CharField(blank=True, max_length=32, verbose_name='الفئة كما وردت')),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('link_note_ar', models.CharField(blank=True, max_length=255, verbose_name='مسوّغ الربط')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_links_made', to=settings.AUTH_USER_MODEL, verbose_name='ربطه')),
                ('linked_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_records', to='people.participant', verbose_name='المشارك المرتبط')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='datamigration.migrationbatch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'مشارك تاريخي',
                'verbose_name_plural': 'المشاركون التاريخيون',
                'ordering': ['batch', 'legacy_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_value', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='قيمة الدورة كما وردت')),
                ('tuition', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رسوم الدورة')),
                ('registration_fee', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رسوم التسجيل')),
                ('collected', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='المقبوض')),
                ('legacy_category', models.CharField(blank=True, max_length=32, verbose_name='الفئة كما وردت')),
                ('source_note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة الملف')),
                ('subject_breakdown', models.JSONField(blank=True, default=dict, verbose_name='توزيع المواد كما ورد')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='datamigration.historicalcohort', verbose_name='الدفعة التاريخية')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='datamigration.historicalparticipant', verbose_name='المشارك')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='datamigration.migrationbatch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'تسجيل تاريخي',
                'verbose_name_plural': 'التسجيلات التاريخية',
                'ordering': ['batch', 'id'],
            },
        ),
        migrations.AddField(
            model_name='historicalcohort',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='datamigration.migrationbatch', verbose_name='الدفعة'),
        ),
        migrations.CreateModel(
            name='MigrationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=120, verbose_name='الورقة')),
                ('source_row', models.PositiveIntegerField(verbose_name='رقم الصف في الملف')),
                ('raw_row', models.JSONField(default=dict, verbose_name='الخلايا كما وردت')),
                ('state', models.CharField(choices=[('RAW', 'خام'), ('VALID', 'صالح للأرشفة'), ('UNIDENTIFIED', 'بلا رقم صالح'), ('REJECTED', 'مرفوض')], default='RAW', max_length=32, verbose_name='الحالة')),
                ('findings', models.JSONField(blank=True, default=list, verbose_name='الملاحظات')),
                ('reason_ar', models.CharField(blank=True, max_length=255, verbose_name='سبب الرفض')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='datamigration.migrationbatch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'صف مصدر',
                'verbose_name_plural': 'صفوف المصدر',
                'ordering': ['batch', 'sheet_name', 'source_row'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ كما ورد')),
                ('legacy_receipt_ref', models.CharField(blank=True, max_length=64, verbose_name='مرجع السند كما ورد')),
                ('legacy_date_text', models.CharField(blank=True, max_length=120, verbose_name='التاريخ كنص')),
                ('parsed_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المفهوم')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='datamigration.historicalenrollment', verbose_name='التسجيل')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='datamigration.migrationbatch', verbose_name='الدفعة')),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_payments', to='datamigration.migrationrow', verbose_name='الصف المصدر')),
            ],
            options={
                'verbose_name': 'مقبوض تاريخي',
                'verbose_name_plural': 'المقبوضات التاريخية',
                'ordering': ['batch', 'id'],
            },
        ),
        migrations.AddField(
            model_name='historicalparticipant',
            name='source_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historical_participant', to='datamigration.migrationrow', verbose_name='الصف المصدر'),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='source_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historical_enrollment', to='datamigration.migrationrow', verbose_name='الصف المصدر'),
        ),
        migrations.AddIndex(
            model_name='migrationbatch',
            index=models.Index(fields=['source_sha256'], name='dm_batch_sha_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationbatch',
            index=models.Index(fields=['status'], name='dm_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='migrationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'VALIDATED', 'COMMITTED', 'SUPERSEDED'])), name='datamigration_batch_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='migrationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMMITTED'), _negated=True), models.Q(('committed_by__isnull', False), ('committed_at__isnull', False)), _connector='OR'), name='datamigration_batch_committed_is_stamped'),
        ),
        migrations.AddConstraint(
            model_name='migrationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMMITTED'), _negated=True), ('validated_at__isnull', False), _connector='OR'), name='datamigration_batch_committed_was_validated'),
        ),
        migrations.AddConstraint(
            model_name='migrationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUPERSEDED'), _negated=True), ('superseded_by__isnull', False), _connector='OR'), name='datamigration_batch_superseded_names_successor'),
        ),
        migrations.AddConstraint(
            model_name='historicalcohort',
            constraint=models.UniqueConstraint(fields=('batch', 'sheet_name'), name='datamigration_cohort_unique_sheet'),
        ),
        migrations.AddIndex(
            model_name='migrationrow',
            index=models.Index(fields=['batch', 'state'], name='dm_row_batch_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='migrationrow',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['RAW', 'VALID', 'UNIDENTIFIED', 'REJECTED'])), name='datamigration_row_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='migrationrow',
            constraint=models.UniqueConstraint(fields=('batch', 'sheet_name', 'source_row'), name='datamigration_row_unique_in_batch'),
        ),
        migrations.AddConstraint(
            model_name='migrationrow',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['RAW', 'VALID']), models.Q(('reason_ar', ''), _negated=True), _connector='OR'), name='datamigration_row_setaside_has_reason'),
        ),
        migrations.AddIndex(
            model_name='historicalpayment',
            index=models.Index(fields=['batch', 'enrollment'], name='dm_pay_batch_enr_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='datamigration_payment_amount_not_negative'),
        ),
        migrations.AddIndex(
            model_name='historicalparticipant',
            index=models.Index(fields=['legacy_number'], name='dm_hist_legacy_no_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalparticipant',
            index=models.Index(fields=['name_ar'], name='dm_hist_name_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalparticipant',
            index=models.Index(fields=['linked_participant'], name='dm_hist_linked_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('legacy_number', ''), _negated=True), name='datamigration_historical_participant_has_number'),
        ),
        migrations.AddConstraint(
            model_name='historicalparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('linked_participant__isnull', True), models.Q(('linked_by__isnull', False), ('linked_at__isnull', False)), _connector='OR'), name='datamigration_link_is_stamped'),
        ),
        migrations.AddIndex(
            model_name='historicalenrollment',
            index=models.Index(fields=['batch', 'cohort'], name='dm_enr_batch_cohort_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('course_value__gte', 0), ('tuition__gte', 0), ('registration_fee__gte', 0), ('collected__gte', 0)), name='datamigration_enrollment_amounts_not_negative'),
        ),
    ]
