# Generated by Django 5.2.17 on 2026-08-15 12:08

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('operations', '0002_cohort_agreement'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز المطالبة')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('trigger_type', models.CharField(max_length=32, verbose_name='مُحفّز المطالبة')),
                ('trigger_reference_ar', models.CharField(blank=True, max_length=255)),
                ('model_snapshot', models.CharField(blank=True, max_length=32)),
                ('rate_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('fixed_amount_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('exclusions_snapshot', models.JSONField(blank=True, default=dict)),
                ('consumables_cap_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('base_mode_snapshot', models.CharField(blank=True, max_length=32)),
                ('gross_collected', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('excluded_registration', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('excluded_consumables', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('excluded_deposits', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('discount_partner_burden', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('distribution_base', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('partner_share', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'مسوّدة'), ('SUBMITTED', 'مرفوعة للاعتماد'), ('APPROVED', 'معتمدة'), ('PAID', 'مصروفة'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='partners.agreement')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims_approved', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='operations.cohort')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims_paid', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='partners.partner')),
            ],
            options={
                'verbose_name': 'مطالبة شريك',
                'verbose_name_plural': 'مطالبات الشركاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number_snapshot', models.CharField(max_length=9)),
                ('participant_name_snapshot', models.CharField(max_length=150)),
                ('enrollment_status_snapshot', models.CharField(max_length=32)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('excluded_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('distribution_base', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('partner_share', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_included', models.BooleanField(default=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=32)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='settlements.partnerclaim')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='operations.enrollment')),
            ],
            options={
                'verbose_name': 'بند مطالبة',
                'verbose_name_plural': 'بنود المطالبات',
                'ordering': ['claim', 'participant_number_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('ineligibility_reason', models.CharField(blank=True, max_length=32)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='المقبوض')),
                ('excluded_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='المستثنى')),
                ('distribution_base', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='وعاء القسمة')),
                ('applied_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('partner_share', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='حصة الشريك')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='partners.agreement')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='operations.enrollment')),
                ('claim_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='settlements.partnerclaimline')),
            ],
            options={
                'verbose_name': 'استحقاق',
                'verbose_name_plural': 'الاستحقاقات',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('obligation_type', models.CharField(choices=[('TRAINER_SALARIES', 'رواتب مدربين'), ('FIELD_TRAINING_EXPENSE', 'مصاريف تدريب عملي'), ('TRAINER_ABSENCE_PENALTY', 'غرامة غياب مدرب'), ('WITHDRAWAL_RETURN', 'إعادة عن انسحاب'), ('REFUND_RECOVERY', 'استرجاع استرداد'), ('ADVANCE_CLAWBACK', 'استرجاع صرف مقدّم')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ')),
                ('statement_reference', models.CharField(blank=True, max_length=255)),
                ('occurred_on', models.DateField()),
                ('absence_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lecture_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('multiplier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'قائم'), ('PARTIALLY_RECOVERED', 'مُستردّ جزئياً'), ('RECOVERED', 'مُستردّ'), ('WAIVED', 'متنازَل عنه')], default='OPEN', max_length=32)),
                ('recovered_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_obligations', to='operations.cohort')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='partners.partner')),
                ('restricted_to_agreement', models.ForeignKey(blank=True, help_text='فارغ = يُحسم من أي مطالبة لهذا الشريك (Q-08)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restricted_obligations', to='partners.agreement', verbose_name='مقيَّد باتفاقية')),
            ],
            options={
                'verbose_name': 'التزام شريك',
                'verbose_name_plural': 'التزامات الشركاء',
                'ordering': ['-occurred_on'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('REFUND_RECOVERY', 'استرجاع استرداد'), ('FIELD_TRAINING', 'مصاريف تدريب عملي'), ('TRAINER_ABSENCE', 'غرامة غياب مدرب'), ('WITHDRAWAL_RETURN', 'إعادة عن انسحاب'), ('ADVANCE_CLAWBACK', 'استرجاع صرف مقدّم'), ('OTHER', 'أخرى')], max_length=32)),
                ('label_ar', models.CharField(max_length=255, verbose_name='البيان')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ')),
                ('source_refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_deductions', to='billing.refund')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='settlements.partnerclaim')),
                ('source_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='settlements.partnerobligation')),
            ],
            options={
                'verbose_name': 'بند حسم',
                'verbose_name_plural': 'بنود الحسم',
                'ordering': ['claim', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('cycle_type', models.CharField(blank=True, max_length=32)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('total_due', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('SIGNED', 'موقّعة')], default='OPEN', max_length=32)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='partners.agreement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='partners.partner')),
            ],
            options={
                'verbose_name': 'مخالصة شريك',
                'verbose_name_plural': 'مخالصات الشركاء',
                'ordering': ['-period_to'],
            },
        ),
        migrations.AddField(
            model_name='partnerclaim',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='settlements.partnersettlement'),
        ),
        migrations.AddConstraint(
            model_name='partnerclaimline',
            constraint=models.UniqueConstraint(fields=('claim', 'enrollment'), name='settlements_claim_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(condition=models.Q(('distribution_base__gte', 0)), name='settlements_entitlement_base_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(condition=models.Q(('is_eligible', True), ('partner_share', 0), _connector='OR'), name='settlements_entitlement_ineligible_earns_nothing'),
        ),
        migrations.AddIndex(
            model_name='partnerobligation',
            index=models.Index(fields=['partner', 'status'], name='stl_obl_partner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerobligation',
            index=models.Index(fields=['restricted_to_agreement'], name='stl_obl_restricted_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerobligation',
            constraint=models.CheckConstraint(condition=models.Q(('obligation_type__in', ['TRAINER_SALARIES', 'FIELD_TRAINING_EXPENSE', 'TRAINER_ABSENCE_PENALTY', 'WITHDRAWAL_RETURN', 'REFUND_RECOVERY', 'ADVANCE_CLAWBACK'])), name='settlements_obligation_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='partnerobligation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'PARTIALLY_RECOVERED', 'RECOVERED', 'WAIVED'])), name='settlements_obligation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='partnerobligation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('recovered_amount__gte', 0), ('recovered_amount__lte', models.F('amount'))), name='settlements_obligation_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='partnerobligation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('obligation_type', 'TRAINER_ABSENCE_PENALTY'), _negated=True), models.Q(('absence_count__isnull', False), ('lecture_cost__isnull', False), ('multiplier__isnull', False)), _connector='OR'), name='settlements_obligation_penalty_has_inputs'),
        ),
        migrations.AddConstraint(
            model_name='claimdeduction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlements_deduction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='claimdeduction',
            constraint=models.CheckConstraint(condition=models.Q(('label_ar', ''), _negated=True), name='settlements_deduction_has_label'),
        ),
        migrations.AddConstraint(
            model_name='partnersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'SIGNED'])), name='settlements_settlement_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='partnersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('balance', django.db.models.expressions.CombinedExpression(models.F('total_due'), '-', models.F('total_paid')))), name='settlements_settlement_balance_equation'),
        ),
        migrations.AddConstraint(
            model_name='partnersettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SIGNED'), _negated=True), ('signed_on__isnull', False), _connector='OR'), name='settlements_settlement_signed_has_date'),
        ),
        migrations.AddIndex(
            model_name='partnerclaim',
            index=models.Index(fields=['partner', 'status'], name='stl_claim_partner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerclaim',
            index=models.Index(fields=['agreement', 'period_from'], name='stl_claim_agr_period_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerclaim',
            index=models.Index(fields=['status', 'created_at'], name='stl_claim_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerclaim',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'PAID', 'CANCELLED'])), name='settlements_claim_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='partnerclaim',
            constraint=models.CheckConstraint(condition=models.Q(('distribution_base', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_collected'), '-', models.F('excluded_registration')), '-', models.F('excluded_consumables')), '-', models.F('excluded_deposits')), '-', models.F('discount_partner_burden')))), name='settlements_claim_base_equation'),
        ),
        migrations.AddConstraint(
            model_name='partnerclaim',
            constraint=models.CheckConstraint(condition=models.Q(('net_payable', django.db.models.expressions.CombinedExpression(models.F('partner_share'), '-', models.F('total_deductions')))), name='settlements_claim_net_equation'),
        ),
        migrations.AddConstraint(
            model_name='partnerclaim',
            constraint=models.CheckConstraint(condition=models.Q(('net_payable__gte', 0)), name='settlements_claim_net_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='partnerclaim',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='settlements_claim_approver_differs'),
        ),
        migrations.AddConstraint(
            model_name='partnerclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), models.Q(('content_hash', ''), _negated=True)), _connector='OR'), name='settlements_claim_approved_is_sealed'),
        ),
    ]
