# Generated by Django 5.2.17 on 2026-08-21 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_clearance_participant_ack'),
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=150, verbose_name='المدرب')),
                ('occurred_on', models.DateField(verbose_name='تاريخ المحاضرة')),
                ('is_waived', models.BooleanField(default=False, verbose_name='حالة طارئة معفاة')),
                ('waiver_approval_ref', models.CharField(max_length=64, verbose_name='مرجع الموافقة الخطية')),
                ('waiver_approval_date', models.DateField(blank=True, null=True)),
                ('note_ar', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_absences', to='operations.cohort', verbose_name='الدفعة')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='settlements.partnerobligation', verbose_name='الغرامة')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'غياب مدرب',
                'verbose_name_plural': 'غيابات المدربين',
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['cohort', 'trainer_name'], name='stl_abs_cohort_trainer_idx'), models.Index(fields=['is_waived'], name='stl_abs_waived_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_waived', False), models.Q(models.Q(('waiver_approval_ref', ''), _negated=True), ('waiver_approval_date__isnull', False)), _connector='OR'), name='settlements_absence_waiver_has_approval'), models.UniqueConstraint(fields=('cohort', 'trainer_name', 'occurred_on'), name='settlements_absence_unique_per_lecture')],
            },
        ),
    ]
