# Generated by Django 5.2.17 on 2026-08-15 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0003_audit_auth_actions'),
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز الدفعة')),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='إلزامي إن كان البرنامج ذا مستويات (BR-011)', null=True, verbose_name='المستوى')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الدفعة')),
                ('starts_on', models.DateField(verbose_name='تبدأ في')),
                ('ends_on', models.DateField(verbose_name='تنتهي في')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='السعة')),
                ('trainer_name', models.CharField(blank=True, max_length=150, verbose_name='المدرب')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='المكان')),
                ('delivery_method', models.CharField(choices=[('IN_PERSON', 'حضوري'), ('ONLINE', 'أونلاين'), ('BLENDED', 'مدمج')], default='IN_PERSON', max_length=32, verbose_name='طريقة التقديم')),
                ('status', models.CharField(choices=[('PLANNED', 'مخطَّطة'), ('PENDING_MOHE', 'بانتظار الوزارة'), ('RUNNING', 'قيد التنفيذ'), ('COMPLETED', 'مكتملة'), ('CANCELLED_LOW_ENROLLMENT', 'ملغاة لقلة التسجيل'), ('MOHE_REJECTED', 'مرفوضة من الوزارة')], default='PLANNED', max_length=32, verbose_name='الحالة')),
                ('lecture_cost', models.DecimalField(blank=True, decimal_places=3, help_text='أساس غرامة غياب المدرب — BR-057 (Sprint 5)', max_digits=12, null=True, verbose_name='كلفة المحاضرة')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='catalog.program', verbose_name='البرنامج')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='core.semester', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-starts_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز التسجيل')),
                ('enrolled_on', models.DateField(verbose_name='تاريخ التسجيل')),
                ('status', models.CharField(choices=[('PENDING_FINANCE', 'بانتظار الدفع'), ('PENDING_APPROVAL', 'بانتظار اعتماد المركز'), ('ACTIVE', 'منتظم'), ('PAYMENT_OVERDUE', 'متأخر عن الدفع'), ('NOT_ATTENDED', 'غير حاضر'), ('INCOMPLETE', 'غير مكمل'), ('WITHDRAWN', 'منسحب'), ('DISMISSED', 'مفصول'), ('TRANSFERRED_OUT', 'منقول منه'), ('DEFERRED', 'مُرحَّل لدفعة لاحقة'), ('CANCELLED', 'ملغى'), ('COMPLETED', 'مكتمل')], default='PENDING_FINANCE', max_length=32, verbose_name='الحالة')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status_note_ar', models.CharField(blank=True, max_length=255)),
                ('lectures_attended', models.PositiveSmallIntegerField(blank=True, help_text='فارغ = لم يُدخَل بعد — ويختلف عن صفر (Q-06)', null=True, verbose_name='عدد المحاضرات')),
                ('attendance_source', models.CharField(blank=True, choices=[('MANUAL', 'إدخال يدوي'), ('SYSTEM', 'من وحدة الحضور')], max_length=32, verbose_name='مصدر العدّاد')),
                ('attendance_record_ref', models.CharField(blank=True, max_length=255, verbose_name='مرجع المصدر')),
                ('attendance_verified_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_note', models.TextField(blank=True)),
                ('voucher_received', models.BooleanField(default=False, verbose_name='استُلم الوصل')),
                ('voucher_received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL)),
                ('attendance_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_attendance', to=settings.AUTH_USER_MODEL, verbose_name='تحقّق منه')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='operations.cohort', verbose_name='الدفعة')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.participant', verbose_name='المشارك')),
                ('price_list', models.ForeignKey(help_text='BR-012 — القائمة التي سُعِّر بها هذا التسجيل', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='catalog.pricelist', verbose_name='قائمة الأسعار')),
                ('voucher_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-enrolled_on', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['program', 'semester'], name='ops_cohort_prog_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['status'], name='ops_cohort_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['starts_on'], name='ops_cohort_starts_idx'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PLANNED', 'PENDING_MOHE', 'RUNNING', 'COMPLETED', 'CANCELLED_LOW_ENROLLMENT', 'MOHE_REJECTED'])), name='operations_cohort_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='operations_cohort_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='operations_cohort_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('lecture_cost__isnull', True), ('lecture_cost__gte', 0), _connector='OR'), name='operations_cohort_lecture_cost_not_negative'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['participant', 'status'], name='ops_enr_part_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['cohort', 'status'], name='ops_enr_cohort_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status', 'enrolled_on'], name='ops_enr_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['price_list'], name='ops_enr_pricelist_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_FINANCE', 'PENDING_APPROVAL', 'ACTIVE', 'PAYMENT_OVERDUE', 'NOT_ATTENDED', 'INCOMPLETE', 'WITHDRAWN', 'DISMISSED', 'TRANSFERRED_OUT', 'DEFERRED', 'CANCELLED', 'COMPLETED'])), name='operations_enrollment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('participant', 'cohort'), name='operations_enrollment_unique_participant_cohort'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('voucher_received', False), ('voucher_received_at__isnull', False), _connector='OR'), name='operations_enrollment_voucher_timestamped'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('approved_at__isnull', True), ('voucher_received', True), _connector='OR'), name='operations_enrollment_no_approval_without_voucher'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('lectures_attended__isnull', True), models.Q(models.Q(('attendance_source', ''), _negated=True), models.Q(('attendance_record_ref', ''), _negated=True), ('attendance_verified_by__isnull', False), ('attendance_verified_at__isnull', False)), _connector='OR'), name='operations_enrollment_attendance_documented'),
        ),
    ]
