# Generated by Django 5.2.17 on 2026-08-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='الاتفاقية التي تحكم قسمة إيراد هذه الدفعة (DATA_MODEL §7.1)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='partners.agreement', verbose_name='الاتفاقية'),
        ),
    ]
