# Generated by Django 5.2.17 on 2026-08-15 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('operations', '0002_cohort_agreement'),
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, verbose_name='من حالة')),
                ('to_status', models.CharField(max_length=32, verbose_name='إلى حالة')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason_ar', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='المرجع')),
            ],
            options={
                'verbose_name': 'سجل حالة تسجيل',
                'verbose_name_plural': 'سجل حالات التسجيل',
                'ordering': ['enrollment', 'changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MoheSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُرسَل للوزارة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=32, verbose_name='الحالة')),
                ('mohe_course_number', models.CharField(blank=True, max_length=64, verbose_name='الرقم الوزاري')),
                ('submitted_on', models.DateField(blank=True, null=True, verbose_name='أُرسل في')),
                ('decided_on', models.DateField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('registration_deadline', models.DateField(blank=True, help_text='BR-015 · BR-019 — بعدها يُمنع رفع أسماء جديدة', null=True, verbose_name='مهلة التسجيل')),
                ('rejection_reason_ar', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('training_axes_ar', models.TextField(blank=True, verbose_name='محاور التدريب')),
                ('practical_aspects_ar', models.TextField(blank=True, verbose_name='الجوانب العملية')),
                ('target_audience_ar', models.TextField(blank=True, verbose_name='الفئة المستهدفة')),
                ('trainer_name', models.CharField(blank=True, max_length=150, verbose_name='المدرب')),
                ('trainer_qualifications', models.TextField(blank=True, verbose_name='مؤهلات المدرب')),
                ('training_location', models.CharField(blank=True, max_length=150, verbose_name='مكان التدريب')),
                ('responsible_entity', models.CharField(blank=True, max_length=150, verbose_name='الجهة المسؤولة')),
                ('approved_key', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب وزاري',
                'verbose_name_plural': 'الطلبات الوزارية',
                'ordering': ['-submitted_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز الحالة')),
                ('case_type', models.CharField(choices=[('CANCELLATION', 'إلغاء'), ('DISMISSAL', 'فصل'), ('DEFERRAL', 'ترحيل لدفعة لاحقة'), ('SUBSTITUTION', 'إحلال'), ('CREDIT_TRANSFER', 'نقل رصيد'), ('CREDIT_BALANCE', 'رصيد دائن')], max_length=32, verbose_name='نوع الحالة')),
                ('occurred_on', models.DateField(verbose_name='تاريخ الحدث')),
                ('detail_ar', models.TextField(verbose_name='التفصيل')),
                ('financial_effect_ar', models.TextField(blank=True, verbose_name='الأثر المالي')),
                ('decision_reference', models.CharField(blank=True, max_length=64, verbose_name='مرجع القرار')),
                ('status', models.CharField(choices=[('OPEN', 'قائمة'), ('SETTLED', 'مسوّاة'), ('CANCELLED', 'ملغاة')], default='OPEN', max_length=32, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حالة خاصة',
                'verbose_name_plural': 'الحالات الخاصة',
                'ordering': ['-occurred_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز النقل')),
                ('requested_on', models.DateField(verbose_name='تاريخ الطلب')),
                ('reason', models.CharField(choices=[('PARTICIPANT_REQUEST', 'طلب المشارك'), ('CENTER_CANCELLATION', 'إلغاء المركز للدورة')], max_length=32, verbose_name='السبب')),
                ('lectures_attended_at_request', models.PositiveSmallIntegerField(default=0, verbose_name='المحاضرات وقت الطلب')),
                ('attendance_record_ref_at_request', models.CharField(blank=True, max_length=255, verbose_name='مرجع العدّاد وقت الطلب')),
                ('same_category', models.BooleanField(default=True, verbose_name='نفس المجال')),
                ('category_waiver_granted', models.BooleanField(default=False, verbose_name='مُنح استثناء المجال')),
                ('category_waiver_reason_ar', models.TextField(blank=True, verbose_name='سبب الاستثناء')),
                ('registration_fee_transferred', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رسم التسجيل المُرحَّل')),
                ('fee_difference', models.DecimalField(decimal_places=3, default=0, help_text='موجب = يدفعه المشارك · سالب = رصيد دائن له (BR-064)', max_digits=12, verbose_name='فرق الرسوم')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING_MANAGER', 'بانتظار تنسيب المدير'), ('PENDING_FINANCE', 'بانتظار تسوية المالية'), ('EXECUTED', 'منفَّذ'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=32, verbose_name='الحالة')),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('finance_settled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason_ar', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نقل',
                'verbose_name_plural': 'عمليات النقل',
                'ordering': ['-requested_on', 'code'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deferred_to',
            field=models.ForeignKey(blank=True, help_text='BR-069 — التسجيل على الدفعة اللاحقة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_from', to='operations.enrollment', verbose_name='رُحِّل إلى'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mohe_uploaded_on',
            field=models.DateField(blank=True, help_text='BR-019 — ضمن المهلة الوزارية وبعد اعتماد التسجيل', null=True, verbose_name='رُفع للوزارة في'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transferred_to',
            field=models.ForeignKey(blank=True, help_text='BR-064 — التسجيل الذي نُقل إليه هذا المشارك', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from', to='operations.enrollment', verbose_name='نُقل إلى'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('mohe_uploaded_on__isnull', True), ('approved_at__isnull', False), _connector='OR'), name='operations_enrollment_upload_needs_approval'),
        ),
        migrations.AddField(
            model_name='enrollmentstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentstatushistory',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.enrollment'),
        ),
        migrations.AddField(
            model_name='mohesubmission',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mohe_submissions', to='operations.cohort', verbose_name='الدفعة'),
        ),
        migrations.AddField(
            model_name='mohesubmission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mohe_submissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mohesubmission',
            name='resubmission_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resubmissions', to='operations.mohesubmission', verbose_name='إعادة إرسال لـ'),
        ),
        migrations.AddField(
            model_name='specialcase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialcase',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_cases', to='operations.enrollment', verbose_name='التسجيل'),
        ),
        migrations.AddField(
            model_name='specialcase',
            name='related_enrollment',
            field=models.ForeignKey(blank=True, help_text='التسجيل الجديد في الترحيل أو الإحلال', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_special_cases', to='operations.enrollment', verbose_name='التسجيل المرتبط'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='category_waiver_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_waivers_granted', to=settings.AUTH_USER_MODEL, verbose_name='مُجيز الاستثناء'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='finance_settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_settled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='operations.enrollment', verbose_name='من تسجيل'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_recommended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='operations.cohort', verbose_name='إلى دفعة'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_enrollment',
            field=models.ForeignKey(blank=True, help_text='فارغ حتى التنفيذ — يُنشأ التسجيل الجديد عندئذ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='operations.enrollment', verbose_name='إلى تسجيل'),
        ),
        migrations.AddIndex(
            model_name='enrollmentstatushistory',
            index=models.Index(fields=['enrollment', 'changed_at'], name='ops_esh_enr_time_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentstatushistory',
            index=models.Index(fields=['to_status', 'changed_at'], name='ops_esh_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='operations_status_history_actually_changes'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['PENDING_FINANCE', 'PENDING_APPROVAL', 'ACTIVE', 'PAYMENT_OVERDUE', 'NOT_ATTENDED', 'INCOMPLETE', 'WITHDRAWN', 'DISMISSED', 'TRANSFERRED_OUT', 'DEFERRED', 'CANCELLED', 'COMPLETED'])), name='operations_status_history_to_status_valid'),
        ),
        migrations.AddIndex(
            model_name='mohesubmission',
            index=models.Index(fields=['cohort', 'status'], name='ops_mohe_cohort_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mohesubmission',
            index=models.Index(fields=['registration_deadline'], name='ops_mohe_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='mohesubmission',
            index=models.Index(fields=['status'], name='ops_mohe_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='mohesubmission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED'])), name='operations_mohe_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='mohesubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(models.Q(('mohe_course_number', ''), _negated=True), ('decided_on__isnull', False)), _connector='OR'), name='operations_mohe_approved_has_number'),
        ),
        migrations.AddConstraint(
            model_name='mohesubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason_ar', ''), _negated=True), _connector='OR'), name='operations_mohe_rejected_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='mohesubmission',
            constraint=models.UniqueConstraint(fields=('cohort', 'approved_key'), name='operations_mohe_one_approval_per_cohort'),
        ),
        migrations.AddIndex(
            model_name='specialcase',
            index=models.Index(fields=['case_type', 'status'], name='ops_sc_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='specialcase',
            index=models.Index(fields=['enrollment'], name='ops_sc_enrollment_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialcase',
            constraint=models.CheckConstraint(condition=models.Q(('case_type__in', ['CANCELLATION', 'DISMISSAL', 'DEFERRAL', 'SUBSTITUTION', 'CREDIT_TRANSFER', 'CREDIT_BALANCE'])), name='operations_special_case_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='specialcase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'SETTLED', 'CANCELLED'])), name='operations_special_case_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='specialcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('case_type', 'DISMISSAL'), _negated=True), models.Q(('decision_reference', ''), _negated=True), _connector='OR'), name='operations_special_case_dismissal_has_reference'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'requested_on'], name='ops_tr_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_enrollment'], name='ops_tr_from_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_cohort'], name='ops_tr_to_cohort_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PENDING_MANAGER', 'PENDING_FINANCE', 'EXECUTED', 'REJECTED'])), name='operations_transfer_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['PARTICIPANT_REQUEST', 'CENTER_CANCELLATION'])), name='operations_transfer_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('category_waiver_granted', False), models.Q(('category_waiver_by__isnull', False), models.Q(('category_waiver_reason_ar', ''), _negated=True), ('reason', 'CENTER_CANCELLATION')), _connector='OR'), name='operations_transfer_waiver_is_justified'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'EXECUTED'), _negated=True), ('to_enrollment__isnull', False), _connector='OR'), name='operations_transfer_executed_has_target'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason_ar', ''), _negated=True), _connector='OR'), name='operations_transfer_rejected_has_reason'),
        ),
    ]
