# Generated by Django 5.2.17 on 2026-08-15 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_credit_return'),
        ('operations', '0003_sprint6_lifecycle'),
        ('people', '0003_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز البراءة')),
                ('case_type', models.CharField(choices=[('GRADUATION', 'تخرج'), ('WITHDRAWAL', 'انسحاب'), ('DISMISSAL', 'فصل')], max_length=32, verbose_name='الحالة')),
                ('opened_on', models.DateField(verbose_name='فُتحت في')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('BLOCKED', 'موقوفة'), ('COMPLETED', 'مكتملة'), ('CANCELLED', 'ملغاة')], default='OPEN', max_length=32, verbose_name='حالة البراءة')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason_ar', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('active_key', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='operations.enrollment')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances_opened', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='people.participant')),
            ],
            options={
                'verbose_name': 'براءة ذمة',
                'verbose_name_plural': 'براءات الذمة',
                'ordering': ['-opened_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=10, unique=True, verbose_name='رقم الشهادة')),
                ('program_name_snapshot', models.CharField(max_length=255, verbose_name='اسم البرنامج')),
                ('duration_text', models.CharField(blank=True, max_length=150, verbose_name='المدة')),
                ('training_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الساعات')),
                ('grade', models.CharField(max_length=32, verbose_name='التقدير')),
                ('grade_source', models.CharField(choices=[('MANUAL', 'إدخال يدوي'), ('CALCULATED', 'محتسب')], default='MANUAL', max_length=32, verbose_name='مصدر التقدير')),
                ('issued_on', models.DateField(verbose_name='تاريخ الإصدار')),
                ('is_replacement', models.BooleanField(default=False, verbose_name='بدل فاقد')),
                ('status', models.CharField(choices=[('ISSUED', 'صادرة'), ('DELIVERED', 'مُسلَّمة'), ('REPLACED', 'استُبدلت')], default='ISSUED', max_length=32, verbose_name='الحالة')),
                ('delivered_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='operations.enrollment')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='people.participant')),
                ('replacement_fee_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_certificates', to='billing.chargeline')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='operations.certificate')),
                ('clearance', models.ForeignKey(blank=True, help_text='إلزامية إلا لبدل الفاقد (BR-075 · C-08)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='operations.clearance')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'ordering': ['-issued_on', 'certificate_number'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(verbose_name='رقم الخطوة')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الخطوة')),
                ('custody_items', models.JSONField(blank=True, default=list, verbose_name='العُهد')),
                ('balance_at_check', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='الرصيد عند الفحص')),
                ('deposit_return_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='مبلغ إعادة التأمين')),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('second_certified_at', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_steps_certified', to=settings.AUTH_USER_MODEL)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='operations.clearance')),
                ('credit_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_steps', to='billing.creditreturn')),
                ('deposit_forfeiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_steps', to='billing.depositforfeiture')),
                ('deposit_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_steps', to='billing.depositreturn')),
                ('second_certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_steps_second_certified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خطوة براءة ذمة',
                'verbose_name_plural': 'خطوات براءة الذمة',
                'ordering': ['clearance', 'step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='clearance',
            index=models.Index(fields=['participant', 'status'], name='ops_clr_part_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clearance',
            index=models.Index(fields=['status', 'opened_on'], name='ops_clr_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='clearance',
            constraint=models.CheckConstraint(condition=models.Q(('case_type__in', ['GRADUATION', 'WITHDRAWAL', 'DISMISSAL'])), name='operations_clearance_case_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='clearance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED'])), name='operations_clearance_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='clearance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='operations_clearance_completed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='clearance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancellation_reason_ar', ''), _negated=True), _connector='OR'), name='operations_clearance_cancelled_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='clearance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'active_key'), name='operations_clearance_one_live_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['participant'], name='ops_cert_participant_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['enrollment'], name='ops_cert_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status', 'issued_on'], name='ops_cert_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ISSUED', 'DELIVERED', 'REPLACED'])), name='operations_certificate_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('grade_source__in', ['MANUAL', 'CALCULATED'])), name='operations_certificate_grade_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('certificate_number__regex', '^[0-9]{10}$')), name='operations_certificate_number_ten_digits'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clearance__isnull', False), ('is_replacement', False)), models.Q(('is_replacement', True), ('replaces__isnull', False)), _connector='OR'), name='operations_certificate_clearance_or_original'),
        ),
        migrations.AddIndex(
            model_name='clearancestep',
            index=models.Index(fields=['clearance', 'is_done'], name='ops_clrstep_done_idx'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.UniqueConstraint(fields=('clearance', 'step_number'), name='operations_clearance_step_unique'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(('step_number__gte', 1), ('step_number__lte', 3)), name='operations_clearance_step_number_range'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('step_number', 2), _negated=True), ('is_done', False), ('balance_at_check', 0), _connector='OR'), name='operations_clearance_step_finance_needs_zero_balance'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(('is_done', False), ('certified_by__isnull', False), _connector='OR'), name='operations_clearance_step_done_has_certifier'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('step_number', 2), _negated=True), ('is_done', False), ('second_certified_by__isnull', False), _connector='OR'), name='operations_clearance_step_finance_needs_second_cert'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(('second_certified_by__isnull', True), models.Q(('second_certified_by', models.F('certified_by')), _negated=True), _connector='OR'), name='operations_clearance_step_second_certifier_differs'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_return_amount__isnull', True), ('step_number', 2), _connector='OR'), name='operations_clearance_step_deposit_fields_on_step_2'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_return__isnull', True), ('deposit_forfeiture__isnull', True), _connector='OR'), name='operations_clearance_step_not_return_and_forfeit'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(('credit_return__isnull', True), ('step_number', 2), _connector='OR'), name='operations_clearance_step_credit_return_on_step_2'),
        ),
    ]
