# Generated by Django 5.2.17 on 2026-08-21 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_credit_return'),
        ('operations', '0004_clearance_and_certificates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancestep',
            name='participant_ack_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إقرار الاستلام'),
        ),
        migrations.AddField(
            model_name='clearancestep',
            name='participant_ack_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم مستلم الشهادة'),
        ),
        migrations.AddConstraint(
            model_name='clearancestep',
            constraint=models.CheckConstraint(condition=models.Q(('step_number', 3), models.Q(('participant_ack_name', ''), ('participant_ack_at__isnull', True)), _connector='OR'), name='operations_clearance_step_ack_on_step_3'),
        ),
    ]
