# Generated by Django 5.2.17 on 2026-09-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0004_alter_auditevent_entity_type'),
        ('operations', '0005_clearance_participant_ack'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='cancellation_reason_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED_LOW_ENROLLMENT'), _negated=True), models.Q(('cancellation_reason_ar', ''), _negated=True), _connector='OR'), name='operations_cohort_cancelled_has_reason'),
        ),
    ]
