# Generated by Django 5.2.17 on 2026-08-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_audit_auth_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='المجال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مجال الدورة',
                'verbose_name_plural': 'مجالات الدورات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='المجال المعرفي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مجال معرفي',
                'verbose_name_plural': 'المجالات المعرفية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='DepositPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم السياسة')),
                ('is_required', models.BooleanField(default=True, help_text='إلزامي على المشارك أم اختياري', verbose_name='إلزامي')),
                ('refund_trigger', models.CharField(help_text='🔴 Q-30 — قيمة قابلة للإعداد بلا قيد قاعدة بيانات', max_length=32, verbose_name='مُحفّز الاسترداد')),
                ('forfeit_on', models.JSONField(blank=True, default=list, help_text='مثال ["DISMISSED", "NOT_ATTENDED"] — 🔴 Q-30', verbose_name='حالات المصادرة')),
                ('is_taxable', models.BooleanField(default=False, help_text='🔴 Q-27 — الافتراض: التأمين التزام لا إيراد فلا يخضع', verbose_name='خاضع للضريبة')),
                ('allows_partial_deduction', models.BooleanField(default=True, verbose_name='يسمح بحسم جزئي')),
                ('claim_deadline_days', models.PositiveSmallIntegerField(blank=True, help_text='فارغ = بلا مهلة سقوط', null=True, verbose_name='مهلة المطالبة بالأيام')),
                ('notes_ar', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'سياسة تأمين',
                'verbose_name_plural': 'سياسات التأمين',
                'ordering': ['name_ar'],
                'constraints': [models.CheckConstraint(condition=models.Q(('claim_deadline_days__isnull', True), ('claim_deadline_days__gt', 0), _connector='OR'), name='catalog_deposit_policy_deadline_positive')],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز القائمة')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم القائمة')),
                ('issued_on', models.DateField(verbose_name='تاريخ الإصدار')),
                ('effective_from', models.DateField(verbose_name='تاريخ السريان')),
                ('proposed_by_text', models.CharField(blank=True, help_text='مدير المركز — BR-008', max_length=150, verbose_name='جهة التنسيب')),
                ('approved_by_text', models.CharField(blank=True, help_text='رئيس الجامعة — خارج النظام (D-31)', max_length=150, verbose_name='جهة الاعتماد')),
                ('decision_reference', models.CharField(blank=True, max_length=64, verbose_name='مرجع القرار')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمدة'), ('ARCHIVED', 'مؤرشفة')], default='DRAFT', max_length=32, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الأرشفة')),
                ('approved_semester_key', models.BigIntegerField(default=None, editable=False, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='core.semester', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'قائمة أسعار',
                'verbose_name_plural': 'قوائم الأسعار',
                'ordering': ['-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز البرنامج')),
                ('program_type', models.CharField(choices=[('DIPLOMA', 'دبلوم تدريبي'), ('SHORT_COURSE', 'دورة قصيرة'), ('ONLINE_COURSE', 'دورة أونلاين')], max_length=32, verbose_name='النوع')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('training_hours', models.PositiveIntegerField(default=0, verbose_name='الساعات التدريبية')),
                ('specialization', models.CharField(blank=True, max_length=150, verbose_name='التخصص')),
                ('is_leveled', models.BooleanField(default=False, verbose_name='ذات مستويات')),
                ('levels_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد المستويات')),
                ('consumables_per_student', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مستهلكات لكل مشارك')),
                ('minimum_first_payment_override', models.DecimalField(blank=True, decimal_places=3, help_text='Q-15 — يتجاوز الإعداد العام عند الحاجة', max_digits=12, null=True, verbose_name='حد أدنى خاص للدفعة الأولى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('course_category', models.ForeignKey(blank=True, help_text='إلزامي للدورات القصيرة — يحدد نطاق النقل المسموح (BR-061)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='catalog.coursecategory', verbose_name='مجال الدورة')),
                ('knowledge_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='catalog.knowledgefield', verbose_name='المجال المعرفي')),
            ],
            options={
                'verbose_name': 'برنامج',
                'verbose_name_plural': 'البرامج',
                'ordering': ['program_type', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='للدورات ذات المستويات فقط (BR-011)', null=True, verbose_name='المستوى')),
                ('course_fee', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='رسوم الدورة')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=3, help_text='فارغ = لا تأمين على هذا البرنامج — ويختلف عن صفر (BR-096)', max_digits=12, null=True, verbose_name='مبلغ التأمين')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('level_key', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('deposit_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='catalog.depositpolicy', verbose_name='سياسة التأمين')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.pricelist', verbose_name='قائمة الأسعار')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='catalog.program', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'بند سعر',
                'verbose_name_plural': 'بنود الأسعار',
                'ordering': ['price_list', 'program', 'level_key'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_category', models.CharField(max_length=32, verbose_name='فئة المشارك')),
                ('fee', models.DecimalField(blank=True, decimal_places=3, help_text='فارغ = بلا رسوم تسجيل — ويختلف عن صفر', max_digits=12, null=True, verbose_name='الرسم')),
                ('exception_note_ar', models.CharField(blank=True, max_length=255, verbose_name='سبب الاستثناء')),
                ('program_key', models.BigIntegerField(default=0, editable=False)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_fee_rules', to='catalog.pricelist', verbose_name='قائمة الأسعار')),
                ('program', models.ForeignKey(blank=True, help_text='فارغ = القاعدة العامة لكل البرامج', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_fee_rules', to='catalog.program', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'قاعدة رسم تسجيل',
                'verbose_name_plural': 'قواعد رسوم التسجيل',
                'ordering': ['price_list', 'program_key', 'participant_category'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='التسلسل')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم المادة')),
                ('training_hours', models.PositiveIntegerField(default=0, verbose_name='الساعات')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='سعر المادة')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='catalog.program', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['program', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'APPROVED', 'ARCHIVED'])), name='catalog_price_list_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('effective_from__gte', models.F('issued_on'))), name='catalog_price_list_effective_after_issued'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('approved_semester_key',), name='catalog_price_list_one_approved_per_semester'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['program_type'], name='catalog_program_type_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_active'], name='catalog_program_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('program_type__in', ['DIPLOMA', 'SHORT_COURSE', 'ONLINE_COURSE'])), name='catalog_program_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('program_type', 'SHORT_COURSE'), _negated=True), ('course_category__isnull', False), _connector='OR'), name='catalog_program_short_course_has_category'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('is_leveled', False), ('levels_count__gte', 2), _connector='OR'), name='catalog_program_levels_at_least_two'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('consumables_per_student__gte', 0)), name='catalog_program_consumables_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.UniqueConstraint(fields=('price_list', 'program', 'level_key'), name='catalog_price_item_unique_program_level'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('course_fee__gte', 0)), name='catalog_price_item_fee_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__isnull', True), ('deposit_amount__gt', 0), _connector='OR'), name='catalog_price_item_deposit_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit_amount__isnull', True), ('deposit_policy__isnull', True)), models.Q(('deposit_amount__isnull', False), ('deposit_policy__isnull', False)), _connector='OR'), name='catalog_price_item_deposit_paired'),
        ),
        migrations.AddConstraint(
            model_name='registrationfeerule',
            constraint=models.UniqueConstraint(fields=('price_list', 'program_key', 'participant_category'), name='catalog_reg_fee_unique_program_category'),
        ),
        migrations.AddConstraint(
            model_name='registrationfeerule',
            constraint=models.CheckConstraint(condition=models.Q(('fee__isnull', True), ('fee__gte', 0), _connector='OR'), name='catalog_reg_fee_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('program', 'sequence'), name='catalog_subject_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='catalog_subject_price_not_negative'),
        ),
    ]
