# Generated by Django 5.2.17 on 2026-08-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_audit_auth_actions'),
        ('operations', '0005_clearance_participant_ack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رمز القيد')),
                ('category', models.CharField(max_length=32, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ')),
                ('incurred_on', models.DateField(verbose_name='تاريخ الصرف')),
                ('description_ar', models.CharField(max_length=255, verbose_name='البيان')),
                ('reference', models.CharField(max_length=64, verbose_name='رقم الفاتورة أو أمر الصرف')),
                ('status', models.CharField(choices=[('RECORDED', 'مقيَّد'), ('APPROVED', 'معتمَد'), ('REJECTED', 'مرفوض')], default='RECORDED', max_length=32, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note_ar', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة القرار')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='operations.cohort', verbose_name='الدفعة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='قيّده')),
                ('financial_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.financialperiod', verbose_name='الفترة المالية')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-incurred_on', '-id'],
                'indexes': [models.Index(fields=['incurred_on'], name='exp_incurred_idx'), models.Index(fields=['category', 'status'], name='exp_cat_status_idx'), models.Index(fields=['cohort'], name='exp_cohort_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['RECORDED', 'APPROVED', 'REJECTED'])), name='expenses_expense_status_valid'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expenses_expense_amount_positive'), models.CheckConstraint(condition=models.Q(('description_ar', ''), _negated=True), name='expenses_expense_has_description'), models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='expenses_expense_approver_differs'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='expenses_expense_approved_is_stamped')],
            },
        ),
    ]
